project:
  type: website
  output-dir: docs

website:
  title: "Sadie Drucker"
  
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Experience
        menu: 
          - text: OHSU Baker Lab
            href: bakerLab.qmd
          - text: OHSU Schedin Lab 
            
          - text: Scripps College Sheung Lab 
  
      - text: Projects
        menu:
          - text: Mapping Inequality in Los Angeles, California
            href: mappingInequality.qmd
          - text: Art && Code
            href: art.qmd
          - text: Generative Text
            href: generativeText.qmd
      - text: Data Science Blog
        menu:
          - text: CDC Datasets
            href: CDCdatasets.qmd
          - text: Water Insecurity
            href: WaterInsecurity.qmd
          - text: New York Times Headlines
            href: NYTHeadlines.qmd
          - text: Permutations and Penguin Bill Lengths
            href: Permutation.qmd
          - text: Ethics, Data, and Power
            href: ethics.qmd
          - text: Stanford Open Policing Project
            href: stanfordSQL.qmd
          - text: Final Presentation for DS002
            href: pres.qmd
format:
  html:
    theme: journal
    page-layout: full
    css: styles.css
    toc: true
    favicon: tinyBaby.png

editor: visual